@startuml

Consumer -> Thing: POST /fade 2000
Thing --> Consumer: 201 Created /fade/1 

Consumer -> Thing: GET /fade/1
Thing --> Consumer: 200 OK pending

Consumer -> Thing: PUT /fade/1 5000
Thing --> Consumer: 204 No Content

Consumer -> Thing: DELETE /fade/1
Thing --> Consumer: 204 No Content

@enduml