@startuml

Consumer -> TDir: GET /td/fadeTD
TDir --> Consumer: 200 OK <TD1>

Consumer -> Thing: POST /fade
Thing --> Consumer: 201 Created /fade/1

Consumer -> TDir: GET /td/fadeTD
TDir --> Consumer: 200 OK <TD2>

@enduml