@startuml

Consumer -> Thing: POST /fade 2000
activate Thing
' == after 2 seconds ==

Consumer -> Thing: GET /fade/1

Consumer -> Thing: PUT /fade/1 5000

Consumer -> Thing: DELETE /fade/1
deactivate Thing

@enduml